name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    - name: Step 2 - GitHub Action if statement (true)
      env:
        WHO_TO_TRUST: ${{ secrets.check }}
      if:  env.WHO_TO_TRUST == 'check'
      run: echo "I know what the secret token is!"

